/**
 * UPS Developer API — OAuth2 + Pickup Creation.
 *
 * Use when we need to book a UPS pickup at an address that's NOT in our
 * ShipStation account (e.g. Treeco Delta for a Bona replenishment where
 * the label was generated by Amazon's Send-to-Amazon flow, not by us).
 *
 * Env vars:
 *   UPS_CLIENT_ID
 *   UPS_CLIENT_SECRET
 *   UPS_ACCOUNT_NUMBER  — 6-digit UPS account (shipper number)
 *   UPS_HOST            — 'onlinetools.ups.com' (prod) or 'wwwcie.ups.com' (test)
 *
 * Register at https://developer.ups.com/
 *   1. Add application → select "Pickup" API
 *   2. Grant access to your UPS account number
 *   3. Copy Client ID + Client Secret into .env
 */

const https = require('https');

const DEFAULT_HOST = 'onlinetools.ups.com';
let _token = null;
let _tokenExpiresAt = 0;

function host() {
  return (process.env.UPS_HOST || DEFAULT_HOST).replace(/^https?:\/\//, '');
}

function _request({ method, path, headers = {}, body }) {
  return new Promise((resolve, reject) => {
    const payload = typeof body === 'string' ? body : (body ? JSON.stringify(body) : null);
    const hdrs = { Accept: 'application/json', ...headers };
    if (payload) hdrs['Content-Length'] = Buffer.byteLength(payload);
    const req = https.request({
      hostname: host(),
      path,
      method,
      headers: hdrs,
    }, (res) => {
      let data = '';
      res.on('data', (c) => { data += c; });
      res.on('end', () => resolve({ status: res.statusCode, headers: res.headers, body: data }));
    });
    req.on('error', reject);
    req.setTimeout(30000, () => { req.destroy(); reject(new Error('UPS API timeout')); });
    if (payload) req.write(payload);
    req.end();
  });
}

// ── OAuth2 ──────────────────────────────────────────────────────────────────

async function _refreshToken() {
  const id = process.env.UPS_CLIENT_ID?.replace(/"/g, '');
  const secret = process.env.UPS_CLIENT_SECRET?.replace(/"/g, '');
  if (!id || !secret) throw new Error('Missing UPS_CLIENT_ID or UPS_CLIENT_SECRET in env');

  const basic = Buffer.from(`${id}:${secret}`).toString('base64');
  const res = await _request({
    method: 'POST',
    path: '/security/v1/oauth/token',
    headers: {
      Authorization: `Basic ${basic}`,
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: 'grant_type=client_credentials',
  });
  if (res.status !== 200) {
    throw new Error(`UPS OAuth failed: ${res.status} — ${res.body.slice(0, 300)}`);
  }
  const data = JSON.parse(res.body);
  _token = data.access_token;
  _tokenExpiresAt = Date.now() + ((data.expires_in || 3600) - 60) * 1000;
  return _token;
}

async function _getToken() {
  if (_token && Date.now() < _tokenExpiresAt) return _token;
  return _refreshToken();
}

// ── Pickup Creation ─────────────────────────────────────────────────────────
//
// pickupAddress: { companyName, contactName, phone, email?, address1, address2?,
//                  city, stateProvince, postalCode, countryCode, residential? }
// readyTime:  'HH:MM' local 24h (e.g. '13:00')
// closeTime:  'HH:MM' local 24h (e.g. '16:00')
// pickupDate: 'YYYYMMDD' (UPS format) or 'YYYY-MM-DD'
// boxes:      { quantity, totalWeightLb, serviceCode? } — ServiceCode 001=Next Day Air, 002=2nd Day, 003=Ground. Default 003.
// trackingNumbers: optional array — if label is already applied, include to help UPS pre-associate.

async function createPickup({
  pickupAddress,
  readyTime,
  closeTime,
  pickupDate,
  boxes,
  trackingNumbers,
  customerContext,
}) {
  if (!pickupAddress) throw new Error('pickupAddress is required');
  if (!readyTime || !closeTime) throw new Error('readyTime + closeTime required (HH:MM)');
  if (!pickupDate) throw new Error('pickupDate required');
  if (!boxes || !boxes.quantity) throw new Error('boxes.quantity required');

  const accountNumber = process.env.UPS_ACCOUNT_NUMBER?.replace(/"/g, '');
  if (!accountNumber) throw new Error('Missing UPS_ACCOUNT_NUMBER in env');

  const token = await _getToken();

  // Normalize date to YYYYMMDD
  const date = String(pickupDate).replace(/-/g, '');
  const ready = String(readyTime).replace(':', '');
  const close = String(closeTime).replace(':', '');

  const request = {
    PickupCreationRequest: {
      RatePickupIndicator: 'N',
      Shipper: {
        Account: {
          AccountNumber: accountNumber,
          AccountCountryCode: pickupAddress.countryCode || 'CA',
        },
      },
      PickupDateInfo: {
        CloseTime: close,
        ReadyTime: ready,
        PickupDate: date,
      },
      PickupAddress: {
        CompanyName: pickupAddress.companyName || '',
        ContactName: pickupAddress.contactName || pickupAddress.companyName || '',
        AddressLine: [pickupAddress.address1, pickupAddress.address2].filter(Boolean),
        Room: '',
        Floor: '',
        City: pickupAddress.city,
        StateProvince: pickupAddress.stateProvince,
        Urbanization: '',
        PostalCode: String(pickupAddress.postalCode || '').replace(/\s/g, ''),
        CountryCode: pickupAddress.countryCode || 'CA',
        ResidentialIndicator: pickupAddress.residential ? 'Y' : 'N',
        Phone: { Number: pickupAddress.phone || '' },
      },
      AlternateAddressIndicator: 'N',
      PickupPiece: [{
        ServiceCode: boxes.serviceCode || '003', // 003 = UPS Standard / Ground
        Quantity: String(boxes.quantity),
        DestinationCountryCode: boxes.destinationCountryCode || 'CA',
        ContainerCode: '01', // 01 = package
      }],
      TotalWeight: {
        Weight: String(boxes.totalWeightLb),
        UnitOfMeasurement: 'LBS',
      },
      OverweightIndicator: boxes.totalWeightLb > 150 ? 'Y' : 'N',
      PaymentMethod: '00',           // 00 = billed to account
      SpecialInstruction: boxes.specialInstruction || '',
      ReferenceNumber: customerContext || '',
      ShippingLabelsAvailable: trackingNumbers && trackingNumbers.length ? 'Y' : 'N',
    },
  };

  const res = await _request({
    method: 'POST',
    path: '/api/pickupcreation/v2107/pickup',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      transId: `ups-pickup-${Date.now()}`,
      transactionSrc: 'yourfloors-ops',
    },
    body: request,
  });
  if (res.status !== 200 && res.status !== 201) {
    const err = new Error(`UPS createPickup failed: ${res.status} — ${res.body.slice(0, 500)}`);
    err.status = res.status;
    err.body = res.body;
    try { err.parsed = JSON.parse(res.body); } catch {}
    throw err;
  }
  const data = JSON.parse(res.body);
  const resp = data.PickupCreationResponse || data;
  return {
    pickupRequestNumber: resp.PRN || resp.PickupRequestConfirmationNumber,
    rate: resp.RateResult?.GrandTotalOfAllCharge || null,
    raw: resp,
  };
}

module.exports = { createPickup, _refreshToken };
